### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

## Player Count

* Display the total number of players

In [93]:
raw_data_info = {"Total Players":[779]}
data_pd = pd.DataFrame(raw_data_info, columns=["Total Players"])
data_pd

   Total Players
0            779

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [5]:
raw_data_items = {
    "Number of Unique Items": [183], 
    "Average Price": [3.05],
    "Number of Purchases": [780],
    "Total Revenue": [2379.77]
}
items_pd = pd.DataFrame(raw_data_items, columns=["Number of Unique Items", "Average Price", "Number of Purchases", "Total Revenue"])

items_pd

   Number of Unique Items  Average Price  Number of Purchases  Total Revenue
0                     183           3.05                  780        2379.77

# Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [6]:
raw_d = {
    'Gender' : ['Male', 'Female','Other/Non-Disclosed'],
    'Total Count' : ["484", "81", "11"],
    'Percentage of Players':[84.03, 14.06, 1.91]}
df = pd.DataFrame(raw_d)
df

                Gender Total Count  Percentage of Players
0                 Male         484                  84.03
1               Female          81                  14.06
2  Other/Non-Disclosed          11                   1.91


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [11]:
raw_data_avg= {
    'Gender' : ["Female", "Male", "Other/Non-Disclosed"],
    'Purchase Count' : [113, 652, 15],
    'Average Purchase Price' : [3.20, 3.02, 3.35],
    'Total Purchase Value' : [361.94, 1967.64, 50.19],
    'Avg Total Purchase per Person' : [4.47, 4.07, 4.56]}
df = pd.DataFrame(raw_data_avg)
df2 = df.set_index('Gender',drop = True)
df2

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase per Person
Gender,,,,
Female,113,3.20,361.94,4.47
Male,652,3.02,1967.64,4.07
Other/Non-Disclosed,15,3.35,50.19,4.56

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [29]:
purchase_data.groupby('SN').head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

In [34]:
SNNamesList = list(purchase_data['SN'].unique())
NumTimesPurchasedList = []
AgeList = []
for sn in SNNamesList:
    AgeList.append(purchase_data['Age'].loc[purchase_data['SN']==sn].max())
    NumTimesPurchasedList.append(purchase_data['SN'].loc[purchase_data['SN']==sn].count())

In [50]:
newdfreallynewthistime = purchase_data.groupby('SN').sum()
newdfreallynewthistime['Number of Purchases Made']=NumTimesPurchasedList
newdfreallynewthistime

                 Purchase ID  Age  Item ID  Price  Number of Purchases Made
SN
Adairialis76             467   16      123   2.28                         3
Adastirin33              142   35      175   4.48                         1
Aeda94                   388   17      128   4.91                         1
Aela59                    28   21      119   4.32                         1
Aelaria33                630   23      171   1.79                         1
Aelastirin39             984   46      134   7.29                         2
Aelidru27                705   22      183   1.09                         1
Aelin32                  723   60      326   8.98                         2
Aelly27                  471   48      130   6.79                         1
Aellynun67               286   25      153   3.74                         2
Aellyria80               746   23      159   3.08                         3
Aelollo59                634   66      175   5.63                         2
Aenarap34                183   21       15   2.96                         2
Aeral43                  263   24       78   4.40                         1
Aeral68                  674   43       77   4.00                         2
Aeral97                  167   23      157   4.80                         1
Aeralria27                32   10      133   4.09                         1
Aeralstical35            583   20       49   2.96                         3
Aeri84                   303   24       71   1.61                         2
Aerillorin70             381   16       83   3.33                         1
Aerithllora36            852   58      235   8.64                         1
Aerithnucal56            324   15      154   4.40                         1
Aerithnuphos61           517   39      128   4.91                         2
Aerithriaphos45           40   20      143   1.56                         2
Aerithriaphos46          236   16      107   2.18                         2
Aesri53                  541   31      161   1.76                         1
Aesty53                  377   42      178   3.91                         2
Aestysu37                725   50      183   5.38                         1
Aesur96                  468   23       30   2.21                         1
Aesurstilis64            405   25       70   1.03                         2
...                      ...  ...      ...    ...                       ...
Undosia27                229   17       72   3.77                         1
Undosian34               710   42      169   8.30                         1
Undotesta33              704   18       95   4.74                         1
Wailin72                 283   21        9   2.73                         1
Yadacal26                834   30       69   6.54                         1
Yadaisuir65              625   20      133   4.09                         1
Yadam35                  553   28        2   2.48                         1
Yadanu52                  60   34       44   2.38                         1
Yadaphos40               483   60      204   5.35                         1
Yalae81                  452   44      201   6.69                         1
Yalaeria91               681   33       28   1.06                         1
Yaliru88                  59   19      105   3.03                         1
Yalo85                   383   34       11   3.65                         1
Yalostiphos68            518   29      160   4.40                         1
Yana46                   280   20       16   3.55                         1
Yarithllodeu72           364   22       88   3.75                         1
Yarithrgue83             279   20      163   3.45                         1
Yarithrin84              698   30       58   4.14                         1
Yarithsurgue62           231   26      139   4.94                         1
Yarolwen77               696   30       87   4.43                         1
Yasrisu92                 46   27      102   3.44                         1
Yastyriaphos75           340   22       41   4.75                         1
Yasur35                  257   26      175   4.48                         1
Yasur85                  514   21       21   1.10                         1
Yathecal72               777   20       67   3.46                         1
Yathecal82              1400   60      241   6.22                         1
Yathedeu43               688   44      143   6.02                         1
Yoishirrala98            572   17      145   4.58                         1
Zhisrisu83               195   20       85   7.89                         1
Zontibe81               1019   63      247   8.03                         1

[576 rows x 5 columns]

In [51]:
bins = [0,10,15,20,25,30,35,40,1000]
labels = [ "10", "10 to 14", "15 to 19", "20 to 24", "25 to 29", "30 to 34", "35 to 39", "40+"]

#bins = [2.95, 3.82, 18.58, 44.79, 13.37, 9.03, 5.38, 2.08]

newdfreallynewthistime["Price Bin"] = pd.cut(newdfreallynewthistime["Price"], bins=bins, labels=labels)
newdfreallynewthistime

,Purchase ID,Age,Item ID,Price,Number of Purchases Made,Price Bin
SN,,,,,,
Adairialis76,467,16,123,2.28,3,10
Adastirin33,142,35,175,4.48,1,10
Aeda94,388,17,128,4.91,1,10
Aela59,28,21,119,4.32,1,10
Aelaria33,630,23,171,1.79,1,10
Aelastirin39,984,46,134,7.29,2,10
Aelidru27,705,22,183,1.09,1,10
Aelin32,723,60,326,8.98,2,10
Aelly27,471,48,130,6.79,1,10
Aellynun67,286,25,153,3.74,2,10
Aellyria80,746,23,159,3.08,3,10
Aelollo59,634,66,175,5.63,2,10
Aenarap34,183,21,15,2.96,2,10
Aeral43,263,24,78,4.40,1,10
Aeral68,674,43,77,4.00,2,10
Aeral97,167,23,157,4.80,1,10
Aeralria27,32,10,133,4.09,1,10
Aeralstical35,583,20,49,2.96,3,10
Aeri84,303,24,71,1.61,2,10
Aerillorin70,381,16,83,3.33,1,10
Aerithllora36,852,58,235,8.64,1,10
Aerithnucal56,324,15,154,4.40,1,10
Aerithnuphos61,517,39,128,4.91,2,10
Aerithriaphos45,40,20,143,1.56,2,10
Aerithriaphos46,236,16,107,2.18,2,10
Aesri53,541,31,161,1.76,1,10
Aesty53,377,42,178,3.91,2,10
Aestysu37,725,50,183,5.38,1,10
Aesur96,468,23,30,2.21,1,10
Aesurstilis64,405,25,70,1.03,2,10
...,...,...,...,...,...,...
Undosia27,229,17,72,3.77,1,10
Undosian34,710,42,169,8.30,1,10
Undotesta33,704,18,95,4.74,1,10
Wailin72,283,21,9,2.73,1,10
Yadacal26,834,30,69,6.54,1,10
Yadaisuir65,625,20,133,4.09,1,10
Yadam35,553,28,2,2.48,1,10
Yadanu52,60,34,44,2.38,1,10
Yadaphos40,483,60,204,5.35,1,10
Yalae81,452,44,201,6.69,1,10
Yalaeria91,681,33,28,1.06,1,10
Yaliru88,59,19,105,3.03,1,10
Yalo85,383,34,11,3.65,1,10
Yalostiphos68,518,29,160,4.40,1,10
Yana46,280,20,16,3.55,1,10
Yarithllodeu72,364,22,88,3.75,1,10
Yarithrgue83,279,20,163,3.45,1,10
Yarithrin84,698,30,58,4.14,1,10
Yarithsurgue62,231,26,139,4.94,1,10
Yarolwen77,696,30,87,4.43,1,10
Yasrisu92,46,27,102,3.44,1,10
Yastyriaphos75,340,22,41,4.75,1,10
Yasur35,257,26,175,4.48,1,10
Yasur85,514,21,21,1.10,1,10
Yathecal72,777,20,67,3.46,1,10
Yathecal82,1400,60,241,6.22,1,10
Yathedeu43,688,44,143,6.02,1,10
Yoishirrala98,572,17,145,4.58,1,10
Zhisrisu83,195,20,85,7.89,1,10
Zontibe81,1019,63,247,8.03,1,10

In [52]:
newdfreallynewthistime.groupby('Price Bin').count()

           Purchase ID  Age  Item ID  Price  Number of Purchases Made
Price Bin
10                 559  559      559    559                       559
10 to 14            15   15       15     15                        15
15 to 19             2    2        2      2                         2
20 to 24             0    0        0      0                         0
25 to 29             0    0        0      0                         0
30 to 34             0    0        0      0                         0
35 to 39             0    0        0      0                         0
40+                  0    0        0      0                         0

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [80]:
newdfreallynewthistime.head()

,Purchase ID,Age,Item ID,Price,Number of Purchases Made,Price Bin
SN,,,,,,
Adairialis76,467,16,123,2.28,3,10
Adastirin33,142,35,175,4.48,1,10
Aeda94,388,17,128,4.91,1,10
Aela59,28,21,119,4.32,1,10
Aelaria33,630,23,171,1.79,1,10

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [215]:
# Create reference to CSV file
csv_path = "Resources/purchase_data.csv"

# Import the CSV into a pandas DataFrame
total_purchase_df = pd.read_csv(csv_path, low_memory=False)
total_purchase_df.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [54]:
anothernewdf=purchase_data.groupby(['Item ID', 'Item Name']).sum()
anothernewdf
#df = purchase_data.sort_values("Price", ascending=False )

#df.head()

                                                      Purchase ID  Age  Price
Item ID Item Name
0       Splinter                                             1149   74   5.12
1       Crucifer                                             1272   67   9.78
2       Verdict                                              2006  143  14.88
3       Phantomlight                                         2087  155  14.94
4       Bloodlord's Fetish                                   1885  124   8.50
5       Putrid Fan                                           1732   94  16.32
6       Rusty Skull                                           541   45   7.40
7       Thorn, Satchel of Dark Souls                         2190  156   9.31
8       Purgatory, Gem of Regret                             1412   85  11.79
9       Thorn, Conqueror of the Corrupted                     799   96  10.92
10      Sleepwalker                                          1470   98   7.16
11      Brimstone                                            1628  106  18.25
12      Dawne                                                2965  155   6.12
13      Serenity                                             1468   90   5.64
14      Possessed Core                                        788   53   5.22
15      Soul Infused Crystal                                 1217  119  14.80
16      Restored Bauble                                      1268   80  14.20
17      Lazarus, Terror of the Earth                         1514  104   6.80
18      Torchlight, Bond of Storms                            741   37   9.30
19      Pursuit, Cudgel of Necromancy                        4138  186   8.16
20      Netherbane                                           2266  119  16.35
21      Souleater                                            2303  106   5.50
22      Amnesia                                              2509  128  13.08
23      Crucifer                                              251   22   1.99
24      Warped Fetish                                         960  137  19.05
25      Hero Cane                                            2534  140  26.10
26      Unholy Wand                                          1042   50   2.24
27      Riddle, Tribute of Ended Dreams                        68   15   3.30
28      Flux, Destroyer of Due Diligence                      934   54   2.12
29      Chaos, Ender of the End                              2275  129   9.90
...                                                           ...  ...    ...
154     Feral Katana                                         1153  101  17.60
155     War-Forged Gold Deflector                            2326  102   5.05
156     Soul-Forged Steel Shortsword                         2456  100   8.85
157     Spada, Etcher of Hatred                               956   80  19.20
158     Darkheart, Butcher of the Champion                    858   29   4.90
159     Oathbreaker, Spellblade of Trials                    4052  120  21.56
160     Azurewrath                                           2520  122  26.40
161     Devine                                               1689  124   8.80
162     Abyssal Shard                                        1140  111  13.35
163     Thunderfury Scimitar                                 1790  115  17.25
164     Exiled Doomblade                                     2829  132  11.41
165     Bone Crushing Silver Skewer                          1399   99  19.44
166     Thirsty Iron Reaver                                  1329   67   9.21
167     Malice, Legacy of the Queen                          1986   85  14.44
168     Sun Strike, Jaws of Twisted Visions                   482   44   2.96
169     Interrogator, Blood Blade of the Queen               1499  110   8.72
170     Shadowsteel                                          1375   91  15.88
171     Scalpel                                              1343   93   5.37
172     Blade of the Grave                                    997   94  12.56
173     Stormfury Longsword                                   752   71   9.86
174     Primitive Blade                                       657   70  13.88
175     Woeful Adamantite Claymore                            620   91  13.44
176     Relentless Iron Skewer                                664   48   5.68
177     Winterthorn, Defender of Shifting Worlds             1440   51   4.16
178     Oathbreaker, Last Hope of the Breaking Storm         4960  287  50.76
179     Wolf, Promise of the Moonwalker                      1948  126  26.88
180     Stormcaller                                           751   11   3.36
181     Reaper's Toll                                        1278  109   8.30
182     Toothpick                                            1327   67  12.09
183     Dragon's Greatsword                                  1488   66   3.27

[183 rows x 3 columns]

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [92]:
summery_table = anothernewdf.sort_values("Price", ascending=False )
summery_table

                                                      Purchase ID  Age  Price
Item ID Item Name
178     Oathbreaker, Last Hope of the Breaking Storm         4960  287  50.76
82      Nirvana                                              2761  215  44.10
145     Fiery Glass Crusader                                 4345  187  41.22
92      Final Critic                                         3773  195  39.04
103     Singed Scalpel                                       3947  178  34.80
59      Lightning, Etcher of the King                        2571  202  33.84
108     Extraction, Quickblade Of Trembling Hands            3484  223  31.77
78      Glimmer, Ender of the Moon                           3218  160  30.80
72      Winter's Bite                                        3692  165  30.16
60      Wolf                                                 3142  145  28.32
179     Wolf, Promise of the Moonwalker                      1948  126  26.88
160     Azurewrath                                           2520  122  26.40
25      Hero Cane                                            2534  140  26.10
37      Shadow Strike, Glory of Ending Hope                  2277  200  25.28
139     Mercy, Katana of Dismay                              1196  110  24.70
128     Blazeguard, Reach of Eternity                        2359  124  24.55
138     Peacekeeper, Wit of Dark Magic                       1037  105  23.70
141     Persuasion                                           2701  169  22.33
87      Deluge, Edge of the West                             1825  111  22.15
159     Oathbreaker, Spellblade of Trials                    4052  120  21.56
136     Ghastly Adamantite Protector                         1645  169  21.48
65      Conqueror Adamantite Mace                            1847  104  21.20
101     Final Critic                                         2598   71  20.95
102     Avenger                                              1668  162  20.64
133     Faith's Scimitar                                     1601   79  20.45
39      Betrayal, Whisper of Grieving Widows                 1364  123  19.70
111     Misery's End                                         2127  115  19.56
165     Bone Crushing Silver Skewer                          1399   99  19.44
75      Brutality Ivory Warmace                              3661  176  19.36
52      Hatred                                               1968   81  19.36
...                                                           ...  ...    ...
124     Venom Claymore                                       1013   95   5.16
0       Splinter                                             1149   74   5.12
155     War-Forged Gold Deflector                            2326  102   5.05
48      Rage, Legacy of the Lone Victor                       996   44   4.96
158     Darkheart, Butcher of the Champion                    858   29   4.90
51      Endbringer                                            181   16   4.66
134     Undead Crusader                                        97   20   4.50
30      Stormcaller                                           634   45   4.42
135     Warped Diamond Crusader                              1406   72   4.20
91      Celeste                                               318   20   4.17
177     Winterthorn, Defender of Shifting Worlds             1440   51   4.16
70      Hope's End                                           1410   78   4.12
115     Spectral Diamond Doomblade                           1240   46   4.08
69      Frenzy, Defender of the Harvest                       760   47   3.96
47      Alpha, Reach of Ending Hope                           664   31   3.58
180     Stormcaller                                           751   11   3.36
27      Riddle, Tribute of Ended Dreams                        68   15   3.30
183     Dragon's Greatsword                                  1488   66   3.27
31      Trickster                                             932   42   3.10
168     Sun Strike, Jaws of Twisted Visions                   482   44   2.96
90      Betrayer                                              700   31   2.94
33      Curved Axe                                            194   54   2.32
26      Unholy Wand                                          1042   50   2.24
118     Ghost Reaver, Longsword of Magic                      321   33   2.17
28      Flux, Destroyer of Due Diligence                      934   54   2.12
125     Whistling Mithril Warblade                            481   45   2.00
126     Exiled Mithril Longsword                              525   24   2.00
23      Crucifer                                              251   22   1.99
104     Gladiator's Glaive                                    727   20   1.93
42      The Decapitator                                       238   21   1.75

[183 rows x 3 columns]